# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
trigger:
  branches:
    include:
    - main
    - wiki-experts

pool:
  vmImage: ubuntu-latest
 
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
 
- script: |
    python -m pip install --upgrade pip
    pip install -e '.[dev]'
  displayName: 'Install dependencies'
 
- script: |
    pytest -vv
  displayName: 'Test with pytest'
